spring:
  profiles:
    active:
    - dev	
---
spring:
  profiles: dev #user的开发环境
  application:
    name: provider-8001
  datasource:
    url: jdbc:mysql://localhost:3306/zmt_bc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8001

eureka:
  instance:
    #给当前工程起个别名，方便在Eureka界面中查看
    instance-id: user-8001
    #设置为true时，鼠标停留在监控的服务器名称上时，页面左下角会显示IP地址
    prefer-ip-address: true
  client:
    service-url:
      #Eureka客户端和服务端交互地址，也就是注册地址
      defaultZone: http://localhost:7001/eureka/
---
spring:
  profiles: test #user的测试环境
  application:
    name: provider-8002
  datasource:
    url: jdbc:mysql://localhost:3306/zmt_meetao?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8002
eureka:
  instance:
    #给当前工程起个别名，方便在Eureka界面中查看
    instance-id: user-8002
    #设置为true时，鼠标停留在监控的服务器名称上时，页面左下角会显示IP地址
    prefer-ip-address: true
  client:
    service-url:
      #Eureka客户端和服务端交互地址，也就是注册地址
      defaultZone: http://localhost:7001/eureka/